permissions:
  HUB_FULL: fullhub.bypass
  HUB_FLY: hub.fly
  HUB_JOIN_MESSAGE: hub.join.message

edit-mode: false
spawnpoint:

sidebar:
  title: '&d&lPLAZMIX &f&lNETWORK'
  lines:
    - ''
    - ' &fНик: %prefix%%player%'
    - ' &fСтатус: %group%'
    - ''
    - ' &fПеченьки: &6%cookies%'
    - ' &fПлазма: &d%plasma%'
    - ''
    - '    &7www.plazmix.net '